"""remove image_url and product_url

Revision ID: 52c9bcceebff
Revises: ea678e5a9bfa
Create Date: 2026-08-13 14:09:30.036312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52c9bcceebff'
down_revision: Union[str, Sequence[str], None] = 'ea678e5a9bfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_details', 'product_url')
    op.drop_column('product_details', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_details', sa.Column('image_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.add_column('product_details', sa.Column('product_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
